[package]
name = "leptos_chart"
version = { workspace = true }
edition = "2021"
authors = ["LangPham"]
license = "MIT"
repository = "https://github.com/theta-vn/leptos_chart"
description = "Chart library for leptos"
readme = "../README.md"

[dependencies]
<<<<<<< HEAD
leptos = {version = "0.5",  features = ["csr"]}
theta-chart = { version = "0.0.7"}
=======
leptos = { version = "0.5", features = ["csr"] }
theta-chart = { version = "0.0.6" }
>>>>>>> e07dd27 (Make SvgChart and Axes public.)
log = "0.4"

[features]
default = ["csr"]
core = []
SvgChart = ["core"]
Axes = ["core"]
debug = []

PieChart = ["core"]
RadarChart = ["core"]

BarChart = ["core", "Axes"]
BarChartGroup = ["core", "Axes"]
LineChart = ["core", "Axes"]
LineChartGroup = ["core", "Axes"]
ScatterChart = ["core", "Axes"]

csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
